### PR TITLE
Update install instructions with conda

### PR DESCRIPTION
**Pull request by volpatto**
Hi, @simetenn.

Well, first of all, you did an awesome work with this package. Congratulations! Nice lib.

This PR adds instruction to installation. I added Uncertainpy to conda-forge, which is a channel of conda
with a huge community. We try to provide portable solution of packages. As you package is very interesting, I put it in conda. Now, one can install Uncertainpy with a simple:

```console
$ conda install -c conda-forge uncertainpy
```

This will automatically solves any dependency issues.

I hope you would appreciate this small contribution.

Best regards,
Diego.

### CODE REVIEW

**Comment by volpatto** [comment]
Ah, another point: Would you like to be add as one of the maintainers of the Uncertainpy's conda feedstock? If you don't want, there is no problem. Actually I'm the only maintainer, but this is fine as well.

**Comment by simetenn** [comment]
Hi Diego,

Thanks for those kind words! That is a great initiative, thanks! I will merge this PR. And yes, it would be interesting to be added as a maintainer.

Kind regards
Simen

**Comment by volpatto** [comment]
Nice to hear it from you, Simen! 

I will add you as a maintainer in the next hours. By doing so, you will be add to the conda-forge members as well. This is necessary to give you write permission in the Uncertainpy recipe repository.

Best regards,
Diego.

**Comment by simetenn** [comment]
I recieved and accepted the invitasion :+1:

**Pull request merged**
